apiVersion: v1
kind: Pod
metadata:
  name: go-hello-world
  labels:
    client: internal
    version: 1.0.0
    environtment: dev
  annotations:
    description: Practice Kubernetes Pod
spec:
  containers:
    - name: go-hello-world
      image: momo89/go-hello-world
      ports:
        - containerPort: 8782
      livenessProbe:
        httpGet:
          path: /ping
          port: 80
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ping
          port: 80
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /ping
          port: 80
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3