apiVersion: v1
kind: ReplicationController
metadata:
  name: go-hostname-rc
  labels:
    client: internal
    version: 1.0.0
    environtment: dev
  annotations:
      description: Practice Kubernetes Replication Controller
spec:
  replicas: 3
  selector:
    app: go-hostname
  template:
    metadata:
      name: go-hostname-pod
      labels:
        app: go-hostname
    spec:
      containers:
        - name: go-hostname
          image: momo89/go-hostname
          ports:
            - containerPort: 9792

