apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-hostname-rs
  labels:
    client: internal
    version: 1.0.0
    environtment: dev
  annotations:
      description: Practice Kubernetes Replication Set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-hostname
  template:
    metadata:
      name: go-hostname-pod
      labels:
        app: go-hostname
    spec:
      containers:
        - name: go-hostname
          image: momo89/go-hostname
          ports:
            - containerPort: 9792

